apiVersion: v1
kind: Service
metadata:
  name: secure-k8s
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: secure-k8s
