apiVersion: v1
kind: Service
metadata:
  name: k8sSecure
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.1.200
  ports:
  - port: 80
  selector:
    app: k8sSecure
